version: '2'
services:
  web:
    container_name: web
    command: "bash -c 'npm install && npm start'"
    image: modop/backbone-marionette-es6-node-5:latest
    tty: true
    stdin_open: true
    ports:
     - "9000:9000"
    volumes:
     - .:/data
